iterations:
- name: smc_round
  params:
    verbose: [0]
  init_state_values: [
    0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 1,
    0
  ]
  seed: 42
  state_width: 57
  state_history_depth: 2
init_time_value: 0.0
timesteps_history_depth: 2
